
#ifndef MCU_CFG_H_
#define MCU_CFG_H

#define NUM_MCU_ACTIVATED_CLOCK_GATES          5
#define CONFIGURED_RAM_SECTIONS 2
#define ATTACHED_EXTERNAL_CRYSTAL_VALUE 16000000UL
#define NUM_OF_CLOCK_SETTINGS 2

#endif 
