
#ifndef MCU_CFG_H_
#define MCU_CFG_H

#define NUM_MCU_ACTIVATED_CLOCK_GATES          5

#define CONFIGURED_RAM_SECTIONS 1

#define RAM_SECTION1 0x00
#define RAM_SECTION1_START_ADDR (unsigned long *)0x20000000 
#define RAM_SECTION1_DEFAULT_VAL 0xAABBCCDD
#define RAM_SECTION1_SIZE_BYTES 12

#define ATTACHED_EXTERNAL_CRYSTAL_VALUE 16000000UL
#define NUM_OF_CLOCK_SETTINGS 2

#define MOSC_CLOCK_SETTINGS 0 
#define PLL_CLOCK_SETTINGS 1 

#endif 
